xcodeproj 'GoogleDrive.xcodeproj'
platform :ios, '7.0'
      
pod 'AeroGear-Store',  :git => 'https://github.com/corinnekrych/aerogear-ios-store.git'
pod 'AeroGear-Pipe',  :git => 'https://github.com/corinnekrych/aerogear-ios-pipe.git'
pod 'AeroGear-OAuth',  :git => 'https://github.com/corinnekrych/aerogear-ios-oauth.git'
pod 'SVProgressHUD', '1.0'