source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Incognito.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/corinnekrych/aerogear-ios-http-1.git", :branch => "oauth1.support"
pod 'AeroGearOAuth1', :git => "https://github.com/corinnekrych/aerogear-ios-oauth1.git"

