source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Weather.xcodeproj'
platform :ios, '7.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/corinnekrych/aerogear-ios-http-1.git", :branch => "deployment.target.7.1"
