source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ChuckNorrisJokes.xcodeproj'
platform :ios, '8.0'
use_frameworks!

pod 'AeroGearHttp', :git => 'https://github.com/corinnekrych/aerogear-ios-http-1.git', :branch => 'swift-2.0'
#pod 'AeroGearJsonSZ', '0.2.0'
