source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ChuckNorrisJokes.xcodeproj'
platform :ios, '7.0'
use_frameworks!

pod 'AeroGearHttp', :git => 'https://github.com/corinnekrych/aerogear-ios-http-1.git', :branch => 'swift2.0-ios7.deployment.target'
#pod 'AeroGearJsonSZ', '0.2.0'
