source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ChuckNorrisJokes.xcodeproj'
platform :ios, '7.0'
use_frameworks!

pod 'AeroGearHttp', :git => "https://github.com/corinnekrych/aerogear-ios-http-1.git", :branch => "deployment.target.7.1"
#pod 'AeroGearJsonSZ', :git => "https://github.com/aerogear/aerogear-ios-jsonsz.git", :branch => "master"
